### ISSUE TITLE
Nearby sharing

### ISSUE THREAD

**Issue by ilyamen** [yggdrasil-network/crispa-android#20]
nearby sharing, can anyone implement yggdrasil work through this?(Yes, the feature is that very few people have, but soon it will all adnroid)

**Comment by vikulin** [comment]
@ilyamen , what do you mean? The Yggdrasil network works through the client.

**Comment by ilyamen** [comment]
I wanted to know if it is possible to unite people (mesh network) using the new android function "nearby sharing" for data transfer


p.s I hope you understand me, my English is very bad

**Comment by vikulin** [comment]
yes, if that function establishes a local link ipv6 for the network
partisipants.

чт, 6 авг. 2020 г. в 00:05, OneQ Project <notifications@github.com>:

**Comment by ilyamen** [comment]
i hope that in the near future we will see a real mesh network based on yggdrasil using ios, android, windows and router.

Maybe someone can get started to implement this? In the future, I want to do it myself, but at the moment I'm too stupid)

**Comment by vikulin** [comment]
Please be more specific asking about your "real mesh network". What are
your expectations describing a use case step-by-step?

чт, 6 авг. 2020 г. в 09:43, OneQ Project <notifications@github.com>:

**Comment by zhoreeq** [comment]
If I understand correctly, "Nearby sharing" is a filesharing feature in Android that works on top of Bluetooth or Wifi Direct. Yggdrasil app already can work on top of Wifi direct, but not on top of "Nearby sharing".

Maybe, there is a way to integrate Wifi-direct peering in the app, by using the same API as "Nearby sharing"? (but that's a topic for another issue)

**Comment by vikulin** [comment]
@zhoreeq WiFi-Direct is a just hardware transport which is the same as local network having no central router. It covers the first and second layers in OSI model. Yggdrasil's purpose to provide TCP/IP transport which is third and fours layers in OSI. "Nearby sharing" works in higher layers exchanging user's data using TCP/IP transport from WiFi-Direct itself and assigning ipv4 and ipv6 local link addresses. You can not just build Yggdrasil on top of "Nearby sharing" since the feature is built on top of TCP/IP.

**Comment by zhoreeq** [comment]
@vikulin ikr? OPs request makes no sense.

**Comment by vikulin** [comment]
@zhoreeq , yep, closing the issue.
