### ISSUE TITLE
Incompatible with 0.4

### ISSUE THREAD

**Issue by jgoerzen** [yggdrasil-network/crispa-android#58]
The releases here and on f-droid are incompatible with 0.4.  This is causing confusion among people visiting the Matrix channel, for instance.  There is an 0.4 version at https://github.com/vikulin/crispa-android/releases .  Could one of the following be done?

1) Pull that one over to here and push it to f-droid

2) Remove the f-droid release and put a warning here that it is broadly incompatible

3) Something else?

**Comment by zhoreeq** [comment]
Something needs to be done. A lot of people say "Yggdrasil is bad, it doesn't work" and it's always about the F-Droid app.

**Comment by ChronosXYZ** [comment]
Pulled and released latest version here.

**Comment by jgoerzen** [comment]
Thank you!  Will this also push to f-droid?

**Comment by DePingus** [comment]
I'm one of the users that ran into the broken app on F-Droid. I agree, either update or remove it. As of today, its still on version 1.7 from 2021-04-04.

I would also like to add, that a large part of my confusion was because I couldn't even tell that the app never connected. It looked connected and never threw an error. I don't know if that's changed for the new version, but its something you might want to look into.

**Comment by ChronosXYZ** [comment]
> Thank you!  Will this also push to f-droid?

Will try to do it.

**Comment by Evanito** [comment]
Asked in the F-Droid matrix room about this app and got the following response from a moderator:
> Different package name = different app. That is how Android is designed. So if the author changes the package name the app will have to be resubmitted to F-Droid and there is no way to update existing users as the Android OS simply doesn't support that

**Comment by vikulin** [comment]
Publish new f droid version for new package

**Comment by vikulin** [comment]
let me know if someone is willing to publish it as a new project on f-droid
